### ISSUE TITLE
PriorityMode doesnt do anything

### ISSUE THREAD

**Issue by ShinyMK** [JakeHL/NitroStream#1]
You can enable/disable it but it doesn't actually do anything.
Instead of True/False allow us to set (0 for Top Screen or 1 For Button Screen).

**Comment by JakeHL** [comment]
This is worded poorly due to my misunderstanding of how priority mode works, however it should work. True works as 1 and false is 0. I'll try and fix this soon.

**Comment by JakeHL** [comment]
This is now fixed.
