### ISSUE TITLE
WSACancelBlockingCall. ERROR

### ISSUE THREAD

**Issue by peleonyt** [JakeHL/NitroStream#10]
Im getting this error "ERR: No se puede escribir datos de en la conexión de transporte: Una operación de bloqueo fue interrumpida por una llamada a WSACancelBlockingCall. "
Sorry is in spanish the error

**Comment by GGLinnk** [comment]
Same error, but in french :
ERR: Impossible de lire les données de la connexion de transport : Une opération de blocage a été interrompue par un appel à WSACancelBlockingCall.

**Comment by JakeHL** [comment]
Please use Kitkat over this application as it is no longer supported. It is easily found on GBA temp & Reddit.
