### ISSUE TITLE
ToolTip on SendMemPatch could be simplified.

### ISSUE THREAD

**Issue by obscurename** [JakeHL/NitroStream#4]
A more user friendly string would be "Some games (OoT, Pokemon, etc.) may disable streaming when launched. Click this before {connecting to the device}|{launching the game} as a solution, however, it may break connecting to the internet within the game."

I've also noticed it says "netowrking" instead of "networking".

**Comment by JakeHL** [comment]
I'll crack on with that! Thanks for the feedback!
