### ISSUE TITLE
Going online in games after memory patch

### ISSUE THREAD

**Issue by xanek** [JakeHL/NitroStream#7]
Unable to access online features after Sending Meory Patch, is there a way to fix this or a workaround?

**Comment by MCJack123** [comment]
The Memory Patch tells the 3DS to stop using Wifi and allow NTR to stream (sort of...), so as far as I know, there is no fix.

**Comment by JakeHL** [comment]
Mouse over the memory patch button for information on this feature or see the GBA Temp post for more information.
