### ISSUE TITLE
Problem with multiple instances of Nitro Stream

### ISSUE THREAD

**Issue by LYNXEMS** [JakeHL/NitroStream#9]
I have a problem with streaming via nitrostream. Streaming from 2 3dses is impossible and I really need that for my channel. I sent the issue as a image. It happens when I connect 2 3dses. It would really help if there is a fix to that. Thanks in advance. Is that actually a problem with Nitro stream or NTR?
![15725752_1833106900245707_1208692770_o](https://cloud.githubusercontent.com/assets/16465347/21485195/36022680-cb9f-11e6-9af5-7f2914842eb2.png)

**Comment by JakeHL** [comment]
it is not possible to stream multiple consoles. This is a limitation of the debugger, not NitroStream.

**Comment by Azurya** [comment]
Owwww that's too bad :( I'm really sad...

**Comment by LYNXEMS** [comment]
What is the limitation actually and is there any other way to do this?

**Comment by Azurya** [comment]
Well the thing is that I have 2 N3DSXL that are ready for streaming and I would like to stream them both, using NTRViewer and NitroStream, it works fine if i connect one or the other but if I connect both first of all the first launched NTRviewer would crash and the second would have like quality: 0% drop:100 with frame skips and all that stuff and the image is flashing or black and shuttery so no way at all to connect 2 3DS on NitroStream, I thought in theory if there was a way to input 2 IP and launch them at the exact same time it would work

**Comment by JakeHL** [comment]
You could use a

virtual machine to host another instance of nitro Stream.

**Comment by Azurya** [comment]
Would that work?

**Comment by Azurya** [comment]
Okay thanks a lot for your help and answers I'll be off trying that thanks again!
